name: NCU Eating Bot TEST & Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MD_SOURCE: ${{ secrets.MD_SOURCE }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
      DEVELOPER_ID: ${{ secrets.DEVELOPER_ID }}
      API_ID: ${{ secrets.API_ID }}
      API_HASH: ${{ secrets.API_HASH }}
      TG_SESSION: ${{ secrets.TG_SESSION }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv

      - name: Setup environment
        run: |          
          pipenv install --dev -e .
          cp filename.txt.example filename.txt

      - name: Test code
        run: |
          pipenv run python -m compileall .

      - name: Run Test
        run: |
          pipenv run pytest --cov-config=.coveragerc --cov=./ tests/

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.ACCOUNT }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/ncu-eating-bot
            git pull 
